[package]
name = "eligibility"
type = "bin"
authors = ["Confidex"]
# Note: Using nargo 1.0.0-beta.13 for Sunspot Groth16 compatibility
# Version constraint removed due to beta version handling in nargo

[dependencies]
