[toolchain]
anchor_version = "0.32.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
confidex_dex = "63bxUBrBd1W5drU5UMYWwAfkMX7Qr17AZiTrm3aqfArB"
arcium_mxe = "DoT4uChyp5TCtkDw4VkUSsmj3u3SFqYQzr2KafrCqYCM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devnet.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
